apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80 # this exposes the service to external traffic
    targetPort: 80 # This is the container/pod port
  type: LoadBalancer