apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytriotasksql 
  labels:
    app: mytriotasksql 
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: mytriotasksql 
  strategy:
    rollingUpdate: 
      maxSurge: 25% 
      maxUnavailable: 25% 
  template:
    metadata:
      labels:
        app: mytriotasksql 
    spec: 
      containers: 
      - name: mytriotasksql 
        image: chrisreeves1/mytriotasksql
        env:
          - name: MYSQL_DATABASE
            value: flask-db
          - name: MYSQL_ROOT_PASSWORD
            value: password
        ports:
          - containerPort: 3306