apiVersion: v1
kind: Service
metadata:
  name: mytriotasksql
spec:
  type: ClusterIP
  ports:
  - name: mytriotasksql
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mytriotasksql